### ISSUE TITLE
DEST_BUCKET policy

### ISSUE THREAD

**Issue by i001962** [evanchiu/serverless-galleria#1]
The Uploader stores images in an S3 bucket. Is there a specific policy that needs to be set on the  bucket that is created manually? Noob here. I'm getting a 403 error after deploying then dropping an image/file on the dropzone in index.html

**Comment by evanchiu** [comment]
No, deploying the uploader will apply a policy to the S3 bucket (See [policy configuration](https://github.com/evanchiu/serverless-galleria/blob/master/uploader/template.yml#L13-L16) in the SAM template).

Do you have a `/` on the end of your path?  One thing I didn't consider when writing these apps was that the API Gateway invoke url can be viewed as `https://invoke.amazonaws.com/Prod` or `https://invoke.amazonaws.com/Prod/`, and the former will lead to the wrong upload paths.

Can you provide the url that's giving you the 403 error? (optionally with the invoke id scrubbed so others can't actually call your stack)

**Comment by i001962** [comment]
The / is missing. I’m unable to test it now but will later today and update this thread. Thanks for the response!

UPDATE - Yes, the missing / was the cause. It works once the / is added.
