### ISSUE TITLE
Mime type is getting changed

### ISSUE THREAD

**Issue by praneshas19901** [evanchiu/serverless-galleria#25]
Can you have this lambda function modified such that it doesn't change the mime type of existing jpeg file to something like   application/octet-stream

**Comment by evanchiu** [comment]
Hello @praneshas19901,

I'm not sure what you mean. The mime type is not part of the file, it's metadata on the http request. The [imageRoute](https://github.com/evanchiu/serverless-galleria/blob/master/galleria/src/index.js#L26) function looks up the mime type and sets it on the response.

**Comment by evanchiu** [comment]
Closing out old issues.
