### ISSUE TITLE
Question: Uploader - large(?) file sizes generate 502 errors

### ISSUE THREAD

**Issue by i001962** [evanchiu/serverless-galleria#3]
@evanchiu just wondering if you've run into any issues loading large (ish) files with uploader? I get a Failed to load resource: the server responded with a status of 502 () when trying to upload a file of 5mb or greater. Any experiences to share on this matter? The issues seems to be caused by the gateway rather than lambda.

**Comment by evanchiu** [comment]
Hello @i001962!

No I haven't personally run into this yet.

From the [API Gateway docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html) it looks like the payload size limit is 10mb, with no way to increase it.  For uploading larger files, you might look at something like [resumable.js](http://www.resumablejs.com), which chunks the files in client-side javascript, with metadata, to enable re-assembling them on the server-side.  For reassembly, each of the chunks could be stored in a separate S3 bucket, with another lambda watching for completion and reassembling into the main bucket.

**Comment by pr3sidentspence** [comment]
I also was hoping to upload larger files (the 10mb stated payload would be enough) but I get an alert that reads "Error uploading [image.jpg]. Max upload size is ~4MB." when trying to upload a 6mb file. I was hoping to find some insight as to where this 4mb restriction is coming from.

While there is no way to self-change the limit, the doc page does say you can request an increase.

**Comment by evanchiu** [comment]
Hello @pr3sidentspence,

While the [API Gateway payload size](https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html) limit is 10mb, the [Lambda invocation payload](https://docs.aws.amazon.com/lambda/latest/dg/limits.html) limit is 6mb.  I added a section about the [uploader limitations](https://github.com/evanchiu/serverless-galleria/tree/master/uploader#limitations) to the readme.

I'd welcome a pull request to support the more complex multi-part upload.
