### ISSUE TITLE
Mobile Uploads

### ISSUE THREAD

**Issue by ATCcodex** [evanchiu/serverless-galleria#4]
Hi @evanchiu ! 

Any chance of adding a way to do uploads from a mobile? All I really need is a button to browse and then a button to submit the file to upload. Thoughts?

**Comment by evanchiu** [comment]
Hello @ATCcodex!

That's a great idea.  As noted in [uploader's index.html](https://github.com/evanchiu/serverless-galleria/blob/master/uploader/public/index.html#L72), I followed a [Netlify example](https://www.netlify.com/blog/2016/11/17/serverless-file-uploads/) for the client side JavaScript.  I haven't looked into what that would require, but I don't expect that I'll be able to prioritize this soon.

**Comment by ATCcodex** [comment]
@evanchiu Ok cool! Thanks! I'll look into it and see if I can figure it out! Thanks!
