### ISSUE TITLE
Can't see the drop point on the web page

### ISSUE THREAD

**Issue by MMichael-S** [evanchiu/serverless-galleria#5]
Hi
After deployment and finished the steps in the setup guide, I can't see the drop point, just see the "INFO" button.

**Comment by evanchiu** [comment]
Hello!

I just deployed a fresh copy to confirm that it works.  I'm not sure which setup guide or "INFO" button you're talking about.  Here's the [readme](https://github.com/evanchiu/serverless-galleria/blob/master/uploader/SAR_README.md) for deploying uploader through the Serverless App Repository.
