### ISSUE TITLE
Uploader barely works,  frustrating.

### ISSUE THREAD

**Issue by linuxtrader** [evanchiu/serverless-galleria#6]
Easy for some,  but this uploader took me some real time to get functional, especially with the custom domain name,  which now works also.      Please, please add to the description that this uploader only works out of the box for small files,  ie.  3MB  or less.      Anything larger than that fails silently, in my case.    Saw the API doc that shows limits of 10MB,   which is still too small,   but I wish I could get even 8MB files to upload.

**Comment by evanchiu** [comment]
Thanks for the note!  Silent failures (or, in this case, worse: failures that report success) are a terrible user experience.  I [updated the readme](https://github.com/evanchiu/serverless-galleria/commit/7e60bc4ea7c0fc53c7883700be326f849d9d4566) with a note and [updated the code](https://github.com/evanchiu/serverless-galleria/commit/a50c46915275f1c165f67e464931698a0fa74966) to check the response and alert on failures with a note about the max size.

If you deploy again, with uploader v1.0.2, you'll get the new functionality.

Thanks!!
