### ISSUE TITLE
Metadata is being removed.

### ISSUE THREAD

**Issue by NirajVisana** [evanchiu/serverless-galleria#68]
Hello, 
I am currently testing compress function for one of our image compression usage but is there any way to maintain metadata, source example image have all the metadata but destination bucket image does not have any metadata attached.

**Comment by evanchiu** [comment]
Hello @NirajVisana,

I think we'd need to update the code to first read the image metadata, then apply it to the resulting image.

I noticed there's an [open issue](https://github.com/oliver-moran/jimp/issues/556) with the library I'm using, jimp, so I don't plan to pursue this. But if you're interested, I'd welcome a pull request!

**Comment by evanchiu** [comment]
Closing out old issues.
