### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by kbaxx** [evanchiu/serverless-galleria#7]
Hey Evan,

I am currently experiencing a CORS issue when I am using the ready to depoy "uploader" cloud-formation on AWS Lambda. What I want to do is that I send an API call from my react app to the API and lambda function. 
Currently I am getting a 403 when I try to POST on the <URL>/Prod/api/file/<FILENAME> path. How can i allow CORS for this API?

**Comment by evanchiu** [comment]
Hello!

To support CORS, I think you can configure the API Gateway to provide appropriate CORS responses to the preflight OPTIONS requests. When you deployed the uploader, it created an API Gateway resource, which you can now modify through the AWS console. Here's API Gateway's documentation to [Enable CORS for an API Gateway REST API Resource](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html).
