### ISSUE TITLE
Crop parameters as variables?

### ISSUE THREAD

**Issue by pr3sidentspence** [evanchiu/serverless-galleria#9]
I'm working on a service to process images, and I need to crop images, but each image will have unique crop parameters. From my reading, it's possible to create lambda function environment variables, but I can't figure out how and where to implement this. Do you have any pointers?

**Comment by evanchiu** [comment]
Sure.  When you deploy the [crop](https://github.com/evanchiu/serverless-galleria/tree/master/crop#deploy-with-cloudformation) application via CloudFormation, the variables pass from your shell into the application.

1. [shell definitions](https://github.com/evanchiu/serverless-galleria/tree/master/crop#deploy-with-cloudformation) provided in the README
1. The [deploy](https://github.com/evanchiu/serverless-galleria/blob/master/crop/package.json#L9) command passes the shell variables as parameters
1. The CloudFormation Stack receives [parameters](https://github.com/evanchiu/serverless-galleria/blob/master/crop/template.yml#L45)
1. The CloudFormation Stack provides [environment variables](https://github.com/evanchiu/serverless-galleria/blob/master/crop/template.yml#L28) to the lambda function
1. The lambda function reads its configuration from [its environment](https://github.com/evanchiu/serverless-galleria/blob/master/crop/src/index.js#L6-L10)

**Comment by pr3sidentspence** [comment]
I don't understand much of that, but hopefully, I will soon :)

Thanks!

**Comment by pr3sidentspence** [comment]
Actually, I'm not following this. Apologies for my AWS noobness. Let's see if I can explain better:

I want to use crop as a lambga function to monitor a bucket for images and crop them. Each image that gets into that bucket will have **unique coordinates** for the crop operation as determined elsewhere. How can I attach those coordinates to the image file (in its name or ~~metadata~~ tags, in a text file with same name, stored in a database, etc.) so that the crop lambda function will use the coordinates determined for that particular image.

I.e., 

1) S3 source bucket sends create event to Crop-Lambda-Function (CLF)
2) CLF reads in source image from source bucket.
3) **CLF reads in crop coordinate (somehow)**
4) CLF performs specified crop and outputs to destination bucket.

(Presumtive) Thanks!

**Comment by pr3sidentspence** [comment]
I think I figured it out. Gonna test. Will post answer if I'm right.

**Comment by evanchiu** [comment]
Hello @pr3sidentspence, I'm closing the thread. It sounds like you have it.  You recognize that for Step 3, there are an unlimited number of ways your lambda can read that data (files in S3, records in a database, make an API call to another service which holds the data, etc.).
